services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=geek'
      - 'POSTGRES_PASSWORD=geekpass'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    container_name: geek_bd

  scylladb:
    image: 'scylladb/scylla:latest'
    ports:
      - '9042:9042'
    container_name: geek_bd_scylla