spring:
  application:
    name: geek
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${JAVAMAIL_EMAIL}
    password: ${JAVAMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.2
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: geekspace
    schema-action: create_if_not_exists
    local-datacenter: datacenter1